In [1]:
#You are given two strings word1 and word2.
# Merge the strings by adding letters in alternating order, starting with word1. If a string is longer than the other, 
# append the additional letters onto the end of the merged string.

word1 = "abc"
word2 = "pqr"
for word1,word2 in zip(word1,word2):
    print(word1,word2,end = " ")


a p b q c r 

In [13]:
d = {1:"key1",1:"key1",2:"key2"}
print(len(d.values()))

2


In [14]:
s = "rohith"
print(s[0])

r


In [15]:
l = ["rohith"]
if l[0] == "rohith":
    print("true")
else:
    print("false")
p = ["ROHITH"]
if "ROHITH" not in p[0]:
    print(True)
else:
    print(False)

true
False


In [1]:
inp1=input("Enter the unit of the temperature(C,c,F,f): ")
inp2=float(input("Enter the temperature value: "))

print("TEMPERATURE CONVERTER")
print("1. Celsius to Farenheit")
print("2.Farenheit to Celsius")
ch=int(input("Enter your choice: "))
if(ch==1 and (inp1!="f" or inp1!="F")):
    res=((9*inp2)/5)+32
    print("{} degrees Celsius is {} degrees Farenheit".format(inp2,res))
    
    

TEMPERATURE CONVERTER
1. Celsius to Farenheit
2.Farenheit to Celsius
0.0 degrees Celsius is 32.0 degrees Farenheit


In [29]:
import itertools
word1 = "abcd"
word2 = "pqrs"
print( ''.join(word1 + word2 for word1,word2 in zip(word1,word2)))


apbqcrds


In [61]:
n = 121
r = str(n)
if r[::-1] == r:
    print(True)
else:
    print(False)

True


In [75]:
prices = [7,1,5,3,6,4]
for i in prices

[1, 3, 4, 5, 6, 7]
6


In [ ]:
prices = [7,1,5,3,6,4]


In [15]:
import tensorflow as tf
import keras
from keras import backend as k
rank_one_tensor = tf.constant([1,2])
print(rank_one_tensor)
rank_two_tensor =tf.constant([[1,2],
                              [3,4]])
rank_two_tensor2 = tf.constant([[1,1],
                                [1,1]])
print(rank_two_tensor)
print("-------------------------------------------")
print(rank_one_tensor*rank_two_tensor)#element wise multiplication
print("-----------------------------------")
print(rank_two_tensor@rank_two_tensor2)#matmultiply
print("-------------------------------------------")
print(rank_two_tensor + rank_two_tensor2)#add
print("---------------------")
print(rank_one_tensor.ndim)
print(rank_two_tensor.dtype)
indices = [0,2]
res = tf.gather(rank_two_tensor,indices , axis = 1)
print(res)


tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
-------------------------------------------
tf.Tensor(
[[1 4]
 [3 8]], shape=(2, 2), dtype=int32)
-----------------------------------
tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)
-------------------------------------------
tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)
---------------------
1
<dtype: 'int32'>
tf.Tensor(
[[1 0]
 [3 0]], shape=(2, 2), dtype=int32)


In [5]:
# import tensorflow as tf
# len(tf.config.list_physical_devices('CPU'))

1

In [20]:
#intuition to find thenumber that is repeated in the array without modifying the array
l = [1,3,4,2,2] 
memo = []
count = 0
for i in l :
    memo.append(i)
    print(memo)
    

[1]
[1, 3]
[1, 3, 4]
[1, 3, 4, 2]
[1, 3, 4, 2, 2]
